language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2

sudo: required
services:
  - docker

addons:
  sonarcloud:
    organization: "lorislab"
    token:
      secure: $SONARCLOUD_KEY

before_install:
  - git clone https://github.com/lorislab/travis-configuration.git .scripts
  - find .scripts -type f -iname "*.sh" -exec chmod +x {} \;

install: ./.scripts/maven/jee/install.sh

script:
  - ./.scripts/maven/jee/build.sh
  - docker pull vromero/activemq-artemis
  - ./.scripts/maven/jee/tests.sh
  - ./.scripts/maven/jee/deploy_master.sh

after_success:
  - ./.scripts/maven/after_success.sh
