language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2

sudo: required
services:
  - docker

addons:
  sonarcloud:
    organization: "lorislab"
    token:
      secure: $SONARCLOUD_KEY

install:
  - git clone https://github.com/lorislab/travis-configuration.git .scripts
  - find .scripts -type f -iname "*.sh" -exec chmod +x {} \;

stages:
  - compile
  - test
  - publish
  - deploy

jobs:
  include:
    - stage: build
      name: Build project
      script:
        - ./.scripts/maven/ci/build.sh
    - stage: test
      name: Integration tests
      script:
        - echo "Integration tets"
    - stage: publish
      name: Publish project
      script:
        - echo "Publish project"
    - stage: deploy
      name: Deploy docker image
      script:
        - echo "Docker push"
