version: "2"

services:

  m6-amq:
    image: vromero/activemq-artemis
    environment:
      DISABLE_SECURITY: "true"
    volumes:
      - ./src/main/docker/artemis:/var/lib/artemis/etc-override
    ports:
      - "8161:8161"
    networks:
      - m6

  m6-example:
    image: lorislab/m6-example
    restart: on-failure
    volumes:
      - "./target/jacocoagent/jacocoagent.jar:/jacocoagent.jar"
    environment:
      JAVA_OPTS: "-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true -javaagent:/jacocoagent.jar=output=tcpserver,address=*"
    ports:
        - "8080:8080"
        - "6300:6300"
        - "9990:9990"
    networks:
     - m6

networks:
    m6:
