version: "2"

services:

  m6-amq:
    image: vromero/activemq-artemis
    environment:
      DISABLE_SECURITY: "true"
    volumes:
      - ./src/main/docker/artemis:/var/lib/artemis/etc-override
    ports:
      - "8161:8161"
    networks:
      - m6

  m6-example:
    image: lorislab/m6-example
    restart: on-failure
    ports:
        - "8080:8080"
        - "9990:9990"
    networks:
     - m6

networks:
    m6:
